server:
  port: 8070
  
spring:
  application:
    name: GroceryApi

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${GROCERIES_PASSWORD}
    url: jdbc:postgresql://${GROCERIES_URL}:5432/${DB_NAME:groceries}
    username: ${GROCERIES_USERNAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}
    show-sql: false
    
