server:
  port: 8080
  
spring:
  application:
    name: icecream-api

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${ICE_CREAM_PASSWORD}
    url: jdbc:postgresql://${ICE_CREAM_URL}:5432/${DB_NAME:ice_cream}
    username: ${ICE_CREAM_USERNAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:public}
    show-sql: false
    
